name: CI

on:
  push:
    branches:
      - main
    workflow_dispatch:


jobs:
  static-analysis:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      # coding style
      - name: EditorConfig-Action
        uses: zbeekman/EditorConfig-Action@v1.1.1

