name: CI

on:
  push:
    branches:
      - main

jobs:
  static-analysis:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: pre-commit check
        run: |
          nix develop --command pre-commit run --all-files
      - name: help commands check
        run: |
          nix develop --command help-commands
      - name: command examples validation
        run: |
          nix develop --command test-command-examples
